language: generic
sudo: required
services:
    - docker

brfore_install:
    - docker build -t pidixit/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true pidixit/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-2-749663592395"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
